[package]
name = "random_thoughts"
version = "0.1.0"
authors = ["Mike Wilhide <wilhide@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
structopt = "0.3.21"
